POST http://localhost:5000/account/code
Content-Type: application/json

{
    "email": "vinhky26032002@gmail.com"
}

###
GET http://localhost:5000/account/captcha

###
POST http://localhost:5000/account/create
Content-Type: application/json

{
    "email": "vinhky26032002@gmail.com",
    "password": "Vinhky2002",
    "name": "vĩnh ký",
    "isAdmin": true,
    "code": "4b7266"
}

###
POST http://localhost:5000/account/login
Content-Type: application/json

{
    "email": "octiu00568@gmail.com",
    "password": "Vinhky2002",
    "captcha": "d90347"
}

###
POST http://localhost:5000/account/email
Content-Type: application/json

{
    "email": "Cfskhanhkhanh@gmail.com"
}

###
PUT http://localhost:5000/account/password
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhY2NvdW50X0lkIjoiZWQ1ZDhjZGYtM2ZhZS00YjQyLWI1Y2MtMTEyYjNjZTlkNzJiIiwicm9sZSI6ImFkbWluIiwiaWF0IjoxNzI0NDA2MTYwLCJleHAiOjE3MjQ0MDcwNjB9.hRnvqdN-HpQTq2csaoNE6p5FnuPHqYMoYq2de2qlxJQ

{
    "password": "Vinhky2002",
    "captcha": "d90347"
}

###
PUT http://localhost:5000/account/forgot
Content-Type: application/json

{
    "email": "Cfskhanhkhanh@gmail.com",
    "password": "Vinhky2002",
    "captcha": "d90347"
}

###
GET http://localhost:5000/account/token

###
DELETE http://localhost:5000/account/logout
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhY2NvdW50X0lkIjoiZWQ1ZDhjZGYtM2ZhZS00YjQyLWI1Y2MtMTEyYjNjZTlkNzJiIiwicm9sZSI6ImFkbWluIiwiaWF0IjoxNzI0NDA2MTYwLCJleHAiOjE3MjQ0MDcwNjB9.hRnvqdN-HpQTq2csaoNE6p5FnuPHqYMoYq2de2qlxJQ

###
GET http://localhost:5000/account/info
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhY2NvdW50X0lkIjoiMThlNzgxNjYtYjQyNy00Y2E4LWFkNTItZDk3YTQ3NTI1YzQ0Iiwicm9sZSI6InVzZXIiLCJpYXQiOjE3MjgzNzUyMTUsImV4cCI6MTcyODQ2MTYxNX0.nQREQDONdI6hdMbY6_o5-UUb8cU-uP2SKQZfcT0XD0U

###
GET http://localhost:5000/account/all?page=1&limit=6&role=jdkadkjbadkbua
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhY2NvdW50X0lkIjoiZWQ1ZDhjZGYtM2ZhZS00YjQyLWI1Y2MtMTEyYjNjZTlkNzJiIiwicm9sZSI6ImFkbWluIiwiaWF0IjoxNzI0NDA4NDA3LCJleHAiOjE3MjQ0MDkzMDd9.-Ti_NUMviS8gPlg9dsFWsezkYmThqZaWXlaFST7rLkI
