###
POST http://localhost:5000/review/create
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhY2NvdW50X0lkIjoiZWQ1ZDhjZGYtM2ZhZS00YjQyLWI1Y2MtMTEyYjNjZTlkNzJiIiwicm9sZSI6ImFkbWluIiwiaWF0IjoxNzI0NTU1MjYzLCJleHAiOjE3MjQ1NTYxNjN9.ychiJj1e0NCkTZGzTX36J7bxHTzaUTTlSr0k4t07_EA

{
    "review_comment": "Lập trình Web cơ bản", 
    "review_rating": 3.5, 
    "student_Id": "888ca0bb-df74-4c22-8b06-c2bdf3f40944", 
    "course_Id": "888ca0bb-df74-4c22-8b06-c2bdf3f40944"
}

###
PUT http://localhost:5000/review/bdf3b1bb-46ba-415e-9b00-a1f09392c170
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhY2NvdW50X0lkIjoiZWQ1ZDhjZGYtM2ZhZS00YjQyLWI1Y2MtMTEyYjNjZTlkNzJiIiwicm9sZSI6ImFkbWluIiwiaWF0IjoxNzI0NTU1MjYzLCJleHAiOjE3MjQ1NTYxNjN9.ychiJj1e0NCkTZGzTX36J7bxHTzaUTTlSr0k4t07_EA

{
    "review_comment": "Lập trình Web cơ bản", 
    "review_rating": 3.5, 
    "student_Id": "888ca0bb-df74-4c22-8b06-c2bdf3f40944", 
    "course_Id": "888ca0bb-df74-4c22-8b06-c2bdf3f40944"
}

###
GET http://localhost:5000/review/info/bdf3b1bb-46ba-415e-9b00-a1f09392c170
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhY2NvdW50X0lkIjoiZWQ1ZDhjZGYtM2ZhZS00YjQyLWI1Y2MtMTEyYjNjZTlkNzJiIiwicm9sZSI6ImFkbWluIiwiaWF0IjoxNzI0NTU1MjYzLCJleHAiOjE3MjQ1NTYxNjN9.ychiJj1e0NCkTZGzTX36J7bxHTzaUTTlSr0k4t07_EA

###
GET http://localhost:5000/review/all?page=1&limit=6&course=bdf3b1bb-46ba-415e-9b00-a1f09392c170
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhY2NvdW50X0lkIjoiZWQ1ZDhjZGYtM2ZhZS00YjQyLWI1Y2MtMTEyYjNjZTlkNzJiIiwicm9sZSI6ImFkbWluIiwiaWF0IjoxNzI0NTU1MjYzLCJleHAiOjE3MjQ1NTYxNjN9.ychiJj1e0NCkTZGzTX36J7bxHTzaUTTlSr0k4t07_EA

###
GET http://localhost:5000/review/all?page=1&limit=6&student=bdf3b1bb-46ba-415e-9b00-a1f09392c170
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhY2NvdW50X0lkIjoiZWQ1ZDhjZGYtM2ZhZS00YjQyLWI1Y2MtMTEyYjNjZTlkNzJiIiwicm9sZSI6ImFkbWluIiwiaWF0IjoxNzI0NTU1MjYzLCJleHAiOjE3MjQ1NTYxNjN9.ychiJj1e0NCkTZGzTX36J7bxHTzaUTTlSr0k4t07_EA


###
DELETE http://localhost:5000/review/bdf3b1bb-46ba-415e-9b00-a1f09392c170
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhY2NvdW50X0lkIjoiZWQ1ZDhjZGYtM2ZhZS00YjQyLWI1Y2MtMTEyYjNjZTlkNzJiIiwicm9sZSI6ImFkbWluIiwiaWF0IjoxNzI0NTU1MjYzLCJleHAiOjE3MjQ1NTYxNjN9.ychiJj1e0NCkTZGzTX36J7bxHTzaUTTlSr0k4t07_EA