###
POST http://localhost:5000/subject/create
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhY2NvdW50X0lkIjoiZWQ1ZDhjZGYtM2ZhZS00YjQyLWI1Y2MtMTEyYjNjZTlkNzJiIiwicm9sZSI6ImFkbWluIiwiaWF0IjoxNzI0NDkxNDY4LCJleHAiOjE3MjQ0OTIzNjh9.ClKiP_E_JnWr_-pdOLIFYj--7D6U-ev26xUkdRtE-KA

{
    "subject_name": "Lập trình Web"
}

###
PUT http://localhost:5000/subject/f58f3fd2-3754-408b-9ee0-ee07e53d5460
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhY2NvdW50X0lkIjoiZWQ1ZDhjZGYtM2ZhZS00YjQyLWI1Y2MtMTEyYjNjZTlkNzJiIiwicm9sZSI6ImFkbWluIiwiaWF0IjoxNzI0NDkxNDY4LCJleHAiOjE3MjQ0OTIzNjh9.ClKiP_E_JnWr_-pdOLIFYj--7D6U-ev26xUkdRtE-KA

{
    "subject_name": "Lập Trình Web"
}

###
GET http://localhost:5000/subject/info/f58f3fd2-3754-408b-9ee0-ee07e53d5460

###
GET http://localhost:5000/subject/all?page=1&limit=6